import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import "swiper/swiper-bundle.css";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Toaster />
        <Providers>
          <Suspense fallback={<h5>Loading ...</h5>}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
