import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import "swiper/swiper-bundle.css";
import { Toaster } from "react-hot-toast";
import FcmTokenComp from "@/components/firebaseForeground";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Toaster />
        <Providers>{children}</Providers>
        <FcmTokenComp />
      </body>
    </html>
  );
}
